package.json
The package.json declares the ISC (default when you use npm init) but the library is actually MIT licensed.
Fixes #76
=> Fix license attribute

ios/RNDocumentPicker/RNDocumentPicker.m
Removes the runtime warning, on at least RN 0.55.2 and newer.
Returns NO as init does not need to run on the main thread.
=> remove runtime warning about requiresMainQueueSetup

ios/RNDocumentPicker/RNDocumentPicker.m
This removes the `init` method which triggered a warning regarding the library requiring main queue setup. Initialization of `composeCallbacks` is now lazily done in the getter. Additionally I removed the `composeViews` ivar because it was not used anywhere (as far as I could see).
=> iOS: Added lazy getter for `composeCallbacks` ivar (fixes requiring main queue setup)

android/build.gradle
This library is not building in the V3 branch
It looks like there has been a breaking change in support for dynamic version dependencies.
I haven't found much documentation about this, but i've seen in Google docs that it's not recommended
https://developer.android.com/studio/releases/gradle-plugin
This same issue is affecting other projects: 
https://github.com/react-native-community/react-native-image-picker/pull/1000
=> v3 - changed dynamic version dependency  to static

android/src/main/java/io/github/elyx0/reactnativedocumentpicker/DocumentPickerModule.java
Gradle started to throw error on build on a missing symbol. This fixes the typo.
=> Missing symbol

index.js
When adding a file i got this promise rejection `You attempted to set the key 'multiple' with the value 'false' on an object that is meant to be immutable and has been frozen.` because `opts` was being modified.
I've changed so `opts` is no longer being modified. 
Also I've added so the `opts`-param  for `pick` and `pickMultiple` is now an empty object instead of overwriting it if there is no opts pressent.
=> default function param + no changing immutable opts

android/src/main/java/com/reactnativedocumentpicker/DocumentPicker.java
When a file larger than 2Gigs is picked (>Int.maxValue) and WritableMap.putInt(FILE_SIZE, size) is invoked, it crashed
=> Fix: exception when picking large files

android/src/main/java/com/reactnativedocumentpicker/DocumentPicker.java
This PR will allow Android to support input of multiple mime types. Not just one.
Previously Android only accepted one mime type even though we could send an array. Now if there is an array of more than one mime type we send this as `EXTRA_MIME_TYPES` to the Intent. 
This makes selection and exclusion of file types much easier.
=> support multiple mime types in android

android/build.gradle
- Gets versions from rootProject with defaults (copied from 66439255158a03fcc450930804f4b3c3a962cfe0).
- Uses implementation instead of compile.
=> Use latest RN android build configuration (v3)

README.md, windows/RNDocumentPicker/RCTDocumentPickerModule.cs
Pull request #93 had an implementation where the picked file was always read directly and supplied in the result js object.
I was against that pull request because the performance hit is pretty huge if every file is being read and added to the javascript object. 
Now I found a use cases which benefits a lot from reading the file directly on windows:
On windows apps can only read the Downloads folder and their own folder by default. Other locations like documents, pictures and removable devices can be accessed by specifying a capability. If a file is outside of these locations it cannot be accessed directly. However if the user picks the file through a file picker permissions to that file are granted implicitly.
> In addition to the default locations, an app can access additional files and …
=> [UWP] Option to read the content of the file directly

__tests__/typescript/index.test.ts, index.d.ts, tsconfig.json
Now index.d.ts has many old breaking types.
I fixed,
then I add type check test and strict type args by union literal types.
=> Fix breaking type definition about typescript

__tests__/typescript/index.test.ts, index.d.ts
In v3, new exported class DocumentPicker as default. I'm sorry I missed this change and add it to fix.
=> fix type by changing default export

__tests__/typescript/index.test.ts, index.d.ts
Based on documentation and how the library works, you are allowed to specify a single specific document type (i.e. "public.png") or an array of document types (["public.png", "public.jpeg"]). 
The previous types only allowed to pick one of the by the library predefined type groups - this adds support for picking one or more specific types instead. 
I've only added a couple of the specific document types here that we use, but adding more is easy for whoever needs them. I also added tests for this.
=> Add support for specifying single or multiple document types

react-native-document-picker.podspec
podspec should point to particular version tag - but the version tags are not present in the repo (last one I see is 2.0.0 even though npm claims 3.2.4 is the latest.) Could you push those tags to github and merge this? Thanks! I'd be interested to become a collaborator if possible, so I could help sort out some other issues. Thanks.
=> fix podspec

ios/RNDocumentPicker/RNDocumentPicker.m
The current way of obtaining the root view controller  appears to not be working in RN 0.59.10. This new approach uses an official [method](https://github.com/facebook/react-native/blob/91681016e84cdb99bd823c937762a0d9974e56fe/React/Base/RCTUtils.h#L87) provided by React Native.
=> iOS: Use official method to get root view controller

index.d.ts, index.js
Makes it possible to select zip files, particularly on iOS where the public.content UTI doesn't include zip archives.
=> Add support for zip extension

README.md, index.d.ts, index.js
As said in #342, the wrong type is used for allFiles. .zip files (and many others) cannot be used.
Using public.item, since both public.content and public.data must conform to public.item.
=> Fix allFiles on iOS

.github/label-actions.yml
motivation: we want to accept only high-quality issues that can be acted upon, not issues that lack necessary information
I will test out shortly, be trying to close some issues
=> chore: add issue actions

.github/label-actions.yml, README.md
motivation: I'd like people who are asking questions to use GH discussions instead of issues in the issue tracker. Issue tracker will be used solely for bugs now.
discussions are available in top menu
=> chore: introduce GH discussions

ios/RNDocumentPicker/RNDocumentPicker.m
See issue: https://github.com/rnmods/react-native-document-picker/issues/276
- Open app
- Open Picker
- Fast double tap pdf document
**Actual**: app freezes and/or creashes.
| iOS     |    ✅    |
| Android |        |
=> Fix crash on iOS

index.d.ts, index.js, windows/RNDocumentPicker/RCTDocumentPickerModule.cs
[Windows only] Adding windows folder picker support into react-native-document-picker
NPM module react-native-document-picker was not having support for Windows Folder picker feature. 
As part of this PR I have implemented this feature. Windows natively provides Folder picker option, similar to Document Picker.  App which require File picker more chances that Folder pick option will also be used, hence its good to provide this feature as well.
This feature is added only for the Windows OS.
=> [Windows] Implementing Folder Picker support

README.md, android/build.gradle, android/src/main/java/io/github/elyx0/reactnativedocumentpicker/DocumentPickerModule.java, react-native-document-picker.podspec
motivation: RN itself now supports only android 5+ and we can simplify our code a little bit thanks to that. 
also closes #317
tested on android devices v6 and v10
=> support only android >=5 (API 21)

android/src/main/java/io/github/elyx0/reactnativedocumentpicker/DocumentPickerModule.java
`copyFile` method is incorrect for Android (haven't checked iOS as I'm not familiar with it).
`InputStream.read` returns the number of bytes read, it may be that only a few bytes are read but the `OutputStream.write` method with one argument always writes the whole buffer even if only the first few bytes are set.
=> Fix copyFile on Android.

android/src/main/java/io/github/elyx0/reactnativedocumentpicker/DocumentPickerModule.java, package.json
If you use `copyTo: 'cachesDirectory'` on Android, it copies the file directly into the cache directory. If there is a file already in there with the same name, it is overwritten. This is different to the behaviour on iOS, where the file is put into a uniquely named sub-directory to ensure it is not overwritten.
I have modified the Android code to take the same approach as on iOS
Configure the picker with  `copyTo: 'cachesDirectory'.`
Open picker on android, select file and then log the `fileCopyUri` 
It will contain a unique subdirectory, i.e. `/data/user/0/[APPID]/cache/[UUID]/[FILENAME]`
| iOS     |       Already Implemented   |
| Android |    ✅    |
=> When using copyTo on android put the file in a uniquely named directory

ios/RNDocumentPicker/RNDocumentPicker.m
Modals on iOS can also be dismissed via user gesture (swiping the modal down).
This PR adds also a listener for that usecase and throws the same error as it would on canceling via cancel button.
closes #364 
Tested on iOS device.
iOS Device
=> feat(ios): listen to user dismiss via swipe down

ios/RNDocumentPicker/RNDocumentPicker.m
UTTypeCreatePreferredIdentifierForTag nullable control added. 
https://github.com/rnmods/react-native-document-picker/issues/394
=> hot fix for silicon mac

README.md, android/src/main/java/io/github/elyx0/reactnativedocumentpicker/DocumentPickerModule.java, index.d.ts, index.js
Resolves https://github.com/rnmods/react-native-document-picker/issues/302
Adds a method to show system directory picker on Android.  Returns the URI of the directory and if possible resolves the URI to the actual path.
=> Android: add pickDirectory

README.md, src/index.tsx, windows/ReactNativeDocumentPicker/RCTDocumentPickerModule.cs
This PR adds Windows support for the pickDirectory() function.
See the official prerequisites for React Native for Windows [here](https://microsoft.github.io/react-native-windows/docs/rnw-dependencies)
Move to the root of the project and run:
`yarn example windows`
| iOS     |    ❌     |
| Android |    ❌     |
| Windows|    ✅     |
- [x ] I have tested this on a device and a simulator
=> Added pickDirectory() implementation for Windows (proper PR)

src/index.tsx
When using `pickSingle` TS incorrectly expects us to array destructure the response, which shouldn't be the case for a single response. 
Since everywhere in the codebase `DocumentPickerResponse[]` is used where it is expected to be an array, the current `Array<{...}>` notation causes TS to mark this as a nested array, instead of just an array.
In this PR I've removed the `Array<>` notation, making the `pickSingle` having a single response, and the `pickMultiple` still having it's array response.
`yarn typescript`
=> fix: TS make DocumentPickerResponse a single response

windows/ReactNativeDocumentPicker/RCTDocumentPickerModule.cs
Added additional + characters by the tool in the previous PR : https://github.com/rnmods/react-native-document-picker/pull/462, it would lead to compilation errors, hence created PR to remove additional character.
| iOS     |    ❌     |
| Android |    ❌     |
| Windows |    ✅   |
=> Updated to remove additional + characters

README.md, android/src/main/java/com/reactnativedocumentpicker/DocumentPickerModule.java, example/ios/Podfile.lock, example/src/App.tsx, ios/RNCPromiseWrapper.h, ios/RNCPromiseWrapper.m, ios/RNDocumentPicker.m, src/index.tsx
adds a promise wrapper on ios that allow to gracefully handle race conditions. 
Closes #393. While I wasn't unfortunately able to reproduce the original issue, this should fix it.
as seen in #393 , open doc picker and tap a file several times in quick succession
=> fix: do not crash on double select

README.md, example/ios/DocumentPickerExample.xcodeproj/project.pbxproj, example/src/App.tsx, ios/RNDocumentPicker.m, src/index.tsx
This allows to set presentation style on ios, see docs.
closes https://github.com/rnmods/react-native-document-picker/issues/398
=> feat: support presentationStyle on ios

README.md, android/src/main/java/com/reactnativedocumentpicker/DocumentPickerModule.java, example/src/App.tsx, ios/RNDocumentPicker.m, src/index.tsx
motivation: `fileCopyUri` is now same as `uri` if no `copyTo` option was provided. This PR makes is so that `fileCopyUri` is specified only if `copyTo` is passed, otherwise is null. This makes the api a little cleaner.
Also made some other minor improvements to code.
tested on ios emulator and android device using the example app
=> feat: fileCopyUri to be null if copyTo not provided

android/build.gradle, package.json
closes #446, flags RNwindows as optional
android: tested in example project and seeing that this influences the "external libraries" in android studio, the settings does have effect
| iOS     |    ❌     |
=> fix: pick up correct android build tools version

android/build.gradle
jCenter will be offline in February 2022. I've updated the android project to use maven.
I've tested the library on a personal project and it builds without issues.
| iOS     |    ✅    |
| Android |    ✅.    |
=> replaced jCenter with mavenCentral

android/src/main/java/com/reactnativedocumentpicker/DocumentPickerModule.java
Make the `fileCopyUri` be a URI string and include the schema prefix (usually `file:/`)
- fixes #526
A URI should begin with the schema prefix
In iOS `fileCopyUri` already works that way
Missing the schema prefix causes a problem when you try to use `fileCopyUri` with `fetch` to upload a file
This was the only method I've found that returned the schema as part of the string
The same thing is used in [RN image picker here](https://github.com/react-native-image-picker/react-native-image-picker/blob/feafc8810420e08af41fe898d9a2372e835185e0/android/src/main/java/com/imagepicker/Utils.java#L397)
Since on `iOS` `fileCopyUri` is returned with a `file:///` prefix - you might be wondering if this is a problem.
According to wikipedia `file:/` and `file:///` are the same thing: …
=> Fix: `fileCopyUri` should include the URI schema

README.md, ios/RNDocumentPicker.m, src/index.tsx
Added `transitionStyle` option on iOS to configure the transition style of the picker.
**Example, `transitionStyle: 'flipHorizontal'`:**
tested on ios emulator using the example app, change `transitionStyle` option.
run the example app
| Android |    ❌     |
=> feat: support transitionStyle on iOS

README.md
Adding on to [this issue](https://github.com/rnmods/react-native-document-picker/issues/553), I wondered why it was claimed that this package is not supported in an Expo project. Mainly due to the fact that the package doesn't require modification of any specific native project files so config plugins are not required. I went ahead to verify this by initializing an Expo project, adding this package and creating a development build of the app, and lo and behold, the package worked flawlessly. So, I would say, the only way this package is unsupported in Expo is by the fact that it doesn't have Expo installation instructions yet. This is what this PR does :)
N/A
- expo project
- apple developer account for testing on a physical iOS device
- add this package by following the installation …
=> docs: add instructions for usage in an Expo project

README.md
this documents the possible need for using `decodeURIComponent` to decode the obtained uri.
also the readme should be a little easier to read (bigger headings)
closes #544
=> docs: document using decodeURIComponent

android/src/main/java/com/reactnativedocumentpicker/DocumentPickerModule.java
This PR fixes issue #513, where even after restricting file types the user could choose any file type (only in case of multiple types)
This is fixed by calling `setType` on ACTION_GET_CONTENT intent with provided `mimeTypes` separated by `|`
The example application is sufficient, provided the emulator/device has some example .doc and .png files
Steps to reproduce the issue - 
* Open the example app (without this commit) on an android device
* Select `Open picker for multi-selection of word files` option
* If there are image files in the gallery, you'll be able to select them
Steps to verify the fix - 
Re-run the app with this commit merged, will only be able to select restricted file types.
| Android |    ✅    |
=> fix: intent type not set in case of multiple mime types filter

android/src/main/java/com/reactnativedocumentpicker/DocumentPickerModule.java
closes #599
closes #119 
tested locally with 3GB file on simulators for both platforms
=> fix(android): support picking 2+ GB files

windows/ReactNativeDocumentPicker/RCTDocumentPickerModule.cs
Closes #511. Allows permission to up to 1,000 directories. [Further reading](https://learn.microsoft.com/en-us/windows/uwp/files/file-access-permissions)
FULL DISCLOSURE: I was unable to get the example to run before making any changes, and haven't fully debugged that, but this change has been tested in my other projects.
No special setup. Simply use Windows.
Open a directory outside of the main app bundle and attempt to do file operations with it.
| Windows|    ✅     |
=> feat(windows): store directory for later access

README.md, example/App.tsx, src/index.tsx
improves docs, removes `pickMultiple` because it can be replaced by `allowMultiSelection`
=> feat: remove pickMultiple

README.md, android/src/main/java/com/reactnativedocumentpicker/RNDocumentPickerModule.java
`onActivityResult` might be called when some other module calls startActivityForResult and we need to ignore those calls. Right now there was a warning logged, which was a false alarm.
tested locally
| iOS     |    ❌     |
=> fix: ignore foreign onActivityResult

README.md
=> docs: better docs around uti+mime

README.md, android/src/main/java/com/reactnativedocumentpicker/RNDocumentPickerModule.java
This fixes a Path Traversal Vulnerability which was present on Android [https://developer.android.com/privacy-and-security/risks/path-traversal](https://developer.android.com/privacy-and-security/risks/path-traversal).
According to CVSS spec, this is a high severity vulnerability [see here](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:L/I:H/A:H). 
The prerequisite is that the user has a malicious app installed on their phone that they can pick files from (think Google Drive or Dropbox, or some File browser app, which is malicious), and that the `copyTo` option is passed to the picking functions.
What could happen is that the `fileName` obtained from a [`Cursor`](https://developer.android.com/reference/android/database/Cursor) when picking a file using the …
=> fix(android): path traversal vulnerability

react-native-document-picker.podspec
This PR fixes a build error related to undefined symbols from MobileCoreServices by linking the MobileCoreServices framework in the podspec
This PR solves issue #713 and issue #685
=> fix: link MobileCoreServices to resolve undefined symbols error on build

android/src/main/java/com/reactnativedocumentpicker/RNDocumentPickerModule.java
Since NativeModule.onCatalystInstanceDestroy() method as deprecated and remove  in new architecture.
(https://github.com/facebook/react-native/commit/18c8417290823e67e211bde241ae9dde27b72f17
=> fix(android): Migrate away from onCatalystInstanceDestroy() to invalidate

react-native-document-picker.podspec
=> Use install_modules_dependencies for React iOS dependencies

.changeset/kind-trains-smoke.md, packages/document-picker/ios/swift/PromiseWrapper.swift
Calling `pick` and then cancelling the picker on iOS will currently throw an error with the code `"E_DOCUMENT_PICKER_CANCELED"`, however it should be throwing with the code `"OPERATION_CANCELED"` to match Android and match the expected value in the JS error codes constant.
JS error codes: https://github.com/react-native-documents/document-picker/blob/74dcb94eb19a748fc61a9916aec127975e19c139/packages/document-picker/src/errors.ts#L5-L39
Android error codes: https://github.com/react-native-documents/document-picker/blob/74dcb94eb19a748fc61a9916aec127975e19c139/packages/document-picker/android/src/main/java/com/reactnativedocumentpicker/PromiseWrapper.java#L14-L15
=> fix(ios): picker cancelled error code to match JS expected value

.github/workflows/ios.yml, packages/document-picker/react-native-document-picker.podspec, packages/document-viewer/react-native-document-viewer.podspec
`install_modules_dependencies` is available on RN 0.71+ which is old enough, and it's available for both old and new arch
=> chore: cleaner podspec

.github/workflows/support.yml
the template path should be relative to issues path
=> chore: update support.yml

.changeset/funny-pugs-cover.md, packages/document-picker/android/src/main/java/com/reactnativedocumentpicker/MetadataGetter.kt, packages/document-picker/android/src/main/java/com/reactnativedocumentpicker/RNDocumentPickerModule.kt
=> fix(android): invalid column flags

.changeset/flat-pumpkins-matter.md, packages/document-picker/android/src/main/java/com/reactnativedocumentpicker/RNDocumentPickerModule.kt
This PR standardizes the response format for directory picking on Android by renaming the `status` key to `bookmarkStatus` when `requestLongTermAccess` is set to `true`. This change ensures consistency across platforms and aligns with the expected type definitions.
- Modified `processDirectoryPickerResult()` method in `RNDocumentPickerModule.kt` to use `bookmarkStatus` instead of `status` in the response object when handling long-term directory access permissions
- Updated `releaseLongTermAccess()` method to also use `bookmarkStatus` instead of `status` in the response for consistency
The changes were made in two specific locations in `packages/document-picker/android/src/main/java/com/reactnativedocumentpicker/RNDocumentPickerModule.kt`:
1. In the `processDirectoryPickerResult()` method …
=> fix(android): correct long term access directory picker response

.changeset/twenty-bikes-hunt.md, packages/document-picker/android/src/main/java/com/reactnativedocumentpicker/FileOperations.kt
- reuse the same, more conservative but proven method of stream copying in `keepLocalCopy` and in `saveDocuments`
- in case of copying between `File*Stream`s , this method should be more efficient on Android >=10
=> refactor: copy streams differently
