- RNDocumentPicker/RNDocumentPicker.m
Currently the menu does not appear when a modal is presenting, because the modal is the root view controller. This should fix it.
> Also show menu when a modal is presenting.

- README.md
- ios/RNDocumentPicker/RNDocumentPicker.m
As #12 is not being updated I've created a new PR with the addition of setting the X and Y position of the required popover on iPads.
> added ipad support

- ios/RNDocumentPicker/RNDocumentPicker.m
Tested on iPhone and iPad simulator.
* note to self: don't copy someone else's PR and expect everything to work
> remove unused popover controller

- README.md
I almost skipped out on the project, because from the example it seemed like it only provides the URI in the response and no mime type or file size or file name.
I haven't reviewed what it does on iOS, hopefully the same.
> Make it clear the lib gives you the metadata

- index.js
Add `video` as a valid predefined file type. Fix #143
> Mime types

- android/src/main/java/io/github/elyx0/reactnativedocumentpicker/DocumentPickerModule.java
Add specific ActivityNotFoundException catch for the case where no ap…p is available to open the desired file type
> Avoid ActivityNotFoundException

- windows/RNDocumentPicker/RCTDocumentPickerModule.cs
- windows/RNDocumentPicker/RNDocumentPicker.csproj
- windows/RNDocumentPicker/project.json
I would really appreciate it, if we could merge this before releasing #69 3.0.0
> [V3] This adds compatibility for react-native-windows 0.57 and fixes some warnings

- README.md
> Update Readme.md for zip file documentation

- README.md
- index.d.ts
- index.js
> Add support for csv files

- .github/FUNDING.yml
as discussed on discord :)
Potential sponsorships will allow me to contribute (bugfixes/features/support/code reviews) more regularly.
> add sponsorship option

- android/src/main/java/io/github/elyx0/reactnativedocumentpicker/DocumentPickerModule.java
This fix is related to bug https://github.com/Elyx0/react-native-document-picker/issues/329
> Get Mime types using readableArrayToStringArray

- react-native-document-picker.podspec
https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
> Fix React dependency to enable XCode 12 build

- README.md
> chore: update discussions in readme

- .github/label-actions.yml
because multiple things can go wrong, we'll need native as well as JS code for fixing bugs
> chore: update comment for closing issues

- __tests__/typescript/index.test.ts
Just deleted a duplicate test case on the `__tests__/typescript/index.test.ts` file.
> Deleted duplicate test case

- .circleci/config.yml
- .github/workflows/nodejs.yml
- example/ios/Podfile.lock
- package-lock.json
Reverts rnmods/react-native-document-picker#447
> Revert "chore: set up automated releases"

- README.md
> docs: remove icloud instructions

- src/index.tsx
It can be useful to have this type exported. The potential use case is having a custom picker extending the document-picker where options also extend DocumentPickerOptions. 
Closes #455 
> fix: TS make DocumentPickerOptions public

- .github/label-actions.yml
- .github/workflows/nodejs.yml
this link to correct issue template and removes automated releases for now
> chore: link to correct issue template

- android/src/main/java/com/reactnativedocumentpicker/DocumentPickerModule.java
- package.json
- src/index.tsx
- yarn.lock
the warning is no longer necessary as autolinking will make linking reliable
closes #152 
> chore: remove jest warning

- .github/label-actions.yml
- .github/workflows/label-actions.yml
this allows to close issues with a comment by applying a label
> chore: automate issue closing by labels

- README.md
> docs: remove outdated example

- example/ios/Podfile.lock
forgot to do this before in #571
> chore: update example lockfile

- CONTRIBUTING.md
The commands for testing the example app, given in contributing guidelines, were outdated
NA
NA
> docs: update scripts in contributing.md

- ios/RNDocumentPicker.mm
closes #591
| Android |    ❌     |
> fix(ios): file copy error handling

- package.json
- packages/document-picker/package.json
- packages/document-viewer/package.json
- packages/example/package.json
A minor update PR to fix : https://github.com/react-native-documents/document-picker/issues/772
> Fix: the license display incorrectly on npmjs.com

- .changeset/big-schools-appear.md
- packages/document-viewer/jest/setup.ts
- packages/document-viewer/src/index.ts
Exports of errors added to index
Tested with the internal examples
Closes #795
> fix: update index.ts for viewer

- .github/workflows/nodejs.yml
- packages/document-viewer/android/src/main/java/com/reactnativedocumentviewer/RNDocumentViewerModule.kt
- packages/document-viewer/package.json
This reverts commit 57a2886cf772a48e32026f9f939a2cbfef4b92cd.
> Revert "fix: remove use of deprecated api (#857)"
